config/routes.rb
Rails.application.routes.draw do
  get 'contacts/index'

  get 'search' => 'articles#search'

  resources :articles

  get '/contacts' => 'home#contacts'

  devise_for :users

  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :users
	validates :title, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    q = params[:q]
    data = Article.all
    if params[:q]
      filtered_data = data.select do |i|
        i[:title].include? params[:q]
      end
      render text: filtered_data.to_json
    else
      render text: data.to_json
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_nav.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Логотип', root_path, class: "navbar-brand"
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li class="#{'active' if controller_name=='home'}"
          a href="/" Главная
        li class="#{'active' if controller_name=='articles'}"
          = link_to 'Статьи', articles_path
        li class="#{'active' if controller_name=='contacts'}"
          = link_to 'Контакты', contacts_index_path
      form.navbar-form.navbar-left role="search"
        .form-group
          input.form-control placeholder="Поиск" type="text"  ng-model="$root.search"
      ul.nav.navbar-nav.navbar-right
        li
          -if user_signed_in?
            span
              = current_user.email
            = link_to 'Logout', destroy_user_session_path, :method => :delete
          -else
            = link_to 'Log in', user_session_path
        
    /! /.navbar-collapse
  /! /.container-fluid

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles
div ng-controller="AjaxCtrl"
  table class="table table-hover"
    thead
      tr
        th Title
        th Description
        th
        -if user_signed_in?
          th
          th

    tbody
        tr ng-repeat="article in search"
          td 
            |{{article.title}}
          td 
            |{{article.description}}
          td.w0 
            a href="articles/{{article.id}}" Просмотр

          -if user_signed_in?
            td.w0 
              a href="articles/edit/{{article.id}}" Изменить
              / td.w0 = link_to 'Destroy', article, data: {:confirm => 'Are you sure?'}, :method => :delete

          
          

  br

  = link_to 'New Article', new_article_path

app/views/articles/new.html.slim
h1 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
p#notice = notice

p
  strong Title:
  = @article.title
p
  strong Description:
  = @article.description
-if user_signed_in?
  = link_to 'Edit', edit_article_path(@article)
  '|
= link_to 'Back', articles_path

app/views/contacts/index.html.slim
h1 Contacts#index
p Find me in app/views/contacts/index.html.slim

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.erb
div
    = link_to 'Articles list', articles_path, :method => :get

app/views/layouts/application.html.slim
<!DOCTYPE html>
html ng-app="app"
head 
  title Resources 
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
body 

  = render partial: "nav"

  .wrap
    = yield